import { randomElement } from './randomUtil';

/*
const _NOUN_ = [
];
*/

/**
 * The list of plural nouns.
 * @const
 */
const _PLURALNOUN_ = [
    "289", "471", "858", "949", "431", 
"936", "777", "562", "971", "325", 
"851", "196", "358", "122", "629", 
"760", "475", "540", "898", "756", 
"774", "652", "692", "545", "693", 
"964", "224", "887", "726", "451", 
"613", "902", "516", "234", "502", 
"884", "680", "763", "957", "133", 
"176", "485", "285", "372", "266", 
"460", "435", "612", "856", "738", 
"996", "581", "434", "610", "937", 
"999", "485", "105", "799", "923", 
"230", "507", "163", "498", "361", 
"486", "230", "961", "664", "786", 
"604", "816", "913", "439", "434", 
"421", "899", "175", "678", "724", 
"380", "264", "786", "662", "766", 
"453", "672", "486", "645", "409", 
"270", "311", "529", "716", "655", 
"719", "469", "804", "716", "494", 
"128", "719", "970", "408", "257", 
"162", "360", "590", "815", "860", 
"617", "685", "270", "502", "980", 
"262", "628", "103", "392", "806", 
"572", "518", "338", "747", "575", 
"878", "643", "889", "836", "941", 
"732", "221", "701", "994", "307", 
"640", "707", "951", "335", "885", 
"156", "628", "616", "990", "441", 
"180", "792", "306", "997", "681", 
"499", "197", "260", "870", "325", 
"478", "509", "669", "416", "957", 
"438", "903", "761", "458", "755", 
"302", "777", "453", "996", "748", 
"124", "250", "329", "591", "291", 
"368", "784", "712", "317", "843", 
"442", "296", "687", "897", "112", 
"377", "925", "146", "271", "585", 
"943", "997", "276", "639", "545", 
"782", "307", "477", "949", "775", 
"856", "951", "526", "278", "789", 
"150", "761", "384", "682", "647", 
"798", "474", "986", "308", "222", 
"722", "866", "317", "319", "996", 
"516", "815", "736", "345", "181", 
"670", "328", "160", "848", "153", 
"177", "289", "777", "432", "993", 
"664", "747", "139", "504", "712", 
"633", "394", "522", "849", "370", 
"741", "606", "493", "280", "438", 
"879", "765", "321", "122", "510", 
"399", "694", "983", "601", "750", 
"955", "470", "872", "513", "150", 
"364", "978", "832", "306", "933", 
"360", "873", "868", "896", "383", 
"174", "415", "142", "127", "609", 
"919", "792", "423", "674", "423", 
"561", "383", "681", "518", "727", 
"940", "580", "874", "558", "563", 
"444", "817", "631", "681", "126", 
"278", "128", "345", "714", "326", 
"675", "405", "398", "896", "639", 
"118", "231", "591", "302", "376", 
"968", "947", "140", "825", "280", 
"568", "951", "679", "464", "715", 
"979", "149", "262", "501", "107", 
"372", "970", "268", "510", "685", 
"338", "984", "317", "211", "398", 
"457", "252", "120", "830", "529", 
"888", "432", "670", "405", "208", 
"298", "417", "342", "753", "394", 
"226", "464", "306", "276", "622", 
"856", "924", "704", "644", "928", 
"969", "657", "102", "689", "483", 
"469", "333", "529", "290", "588", 
"477", "478", "618", "158", "147", 
"449", "962", "793", "517", "523", 
"492", "758", "851", "701", "924", 
"444", "640", "344", "507", "836", 
"898", "740", "611", "471", "831" 
];

/*
const _PLACE_ = [
    'Pub', 'University', 'Airport', 'Library', 'Mall', 'Theater', 'Stadium',
    'Office', 'Show', 'Gallows', 'Beach', 'Cemetery', 'Hospital', 'Reception',
    'Restaurant', 'Bar', 'Church', 'House', 'School', 'Square', 'Village',
    'Cinema', 'Movies', 'Party', 'Restroom', 'End', 'Jail', 'PostOffice',
    'Station', 'Circus', 'Gates', 'Entrance', 'Bridge'
];
*/

/**
 * The list of verbs.
 * @const
 */
    const _VERB_ = [
        "AUU", "XHK", "TAN", "XMJ", "GIE", 
        "NZT", "EYS", "CAQ", "TZT", "OPR", 
        "CDP", "RTD", "SDV", "OMT", "IAD", 
        "RLF", "DDE", "DSA", "PLD", "AUX", 
        "MXG", "ZCL", "YZW", "KRW", "YEW", 
        "RBX", "ERY", "JIG", "JTJ", "AYQ", 
        "FES", "UVS", "IYZ", "CXT", "WJT", 
        "JZL", "NRK", "HKA", "KVX", "TUQ", 
        "AEA", "RXN", "KSD", "TPR", "UYW", 
        "RFP", "LNY", "PVL", "KYC", "LKS", 
        "ZPR", "SZZ", "VGY", "LQX", "PIO", 
        "MIH", "WHF", "FDK", "RMD", "SSZ", 
        "OEE", "XUF", "XSI", "UEI", "ITC", 
        "UUC", "WIA", "RFQ", "WPI", "IBZ", 
        "ZVB", "KSD", "FSG", "DEC", "FPK", 
        "LNY", "OGJ", "EHR", "SSK", "ZXE", 
        "MEK", "TDC", "PSG", "RRT", "NKD", 
        "WRW", "IZN", "WKB", "RFY", "UWC", 
        "DQV", "GYM", "JCC", "PUE", "MJN", 
        "GCT", "FXE", "QCO", "LRS", "CTC", 
        "CKB", "VBP", "DHC", "BIK", "XRU", 
        "ZMM", "HFV", "UIR", "EHO", "VED", 
        "SEH", "YWP", "ZVE", "IST", "SJR", 
        "XFD", "FGG", "PJQ", "AEK", "FSZ", 
        "VZW", "KBM", "TIU", "GCG", "AHT", 
        "RWA", "RCC", "TJN", "REI", "FXU", 
        "BXW", "DHI", "HNA", "XAO", "IMX", 
        "LUN", "QOG", "NWC", "DUW", "IEY", 
        "ZLP", "UVS", "BIA", "GYK", "WZK", 
        "DTN", "ANE", "QSA", "IOB", "TUR", 
        "JKT", "PXK", "VZS", "RSH", "CSB", 
        "KVT", "CDR", "MQT", "MII", "GQV", 
        "JVG", "IKC", "MWY", "SAI", "UJI", 
        "NTX", "LYJ", "KPW", "NAG", "HZS", 
        "OCE", "XMH", "WGS", "MXO", "BZO", 
        "TEI", "QZL", "GTY", "NMU", "MGC", 
        "ZPN", "YHV", "ORE", "ZCX", "COF", 
        "BJJ", "JPP", "GFK", "RBW", "MGT", 
        "YOK", "AFH", "CTW", "SCR", "KQR", 
        "DEY", "ZAJ", "QAV", "XGH", "SPX", 
        "PMC", "FXG", "UEH", "MCF", "MSQ", 
        "KSI", "JBZ", "OZM", "HPK", "JDF", 
        "ASR", "ELE", "JDS", "UWH", "KUC", 
        "DWY", "OXK", "QAI", "XQF", "RLS", 
        "LIP", "DUC", "COH", "WPS", "GGO", 
        "NOS", "SHU", "BRI", "NYH", "QGH", 
        "EST", "MUK", "YBH", "SDK", "BOM", 
        "MKI", "TZB", "OCZ", "NVM", "ZVO", 
        "RQW", "OQI", "NEW", "SHS", "UDO", 
        "JLX", "IZZ", "KNG", "PAN", "NKR", 
        "AMK", "MBU", "NRO", "BVF", "CSN", 
        "FQE", "WQX", "TCN", "EXG", "PDI", 
        "APD", "YVM", "FHP", "STD", "PQF", 
        "PJU", "TTD", "CZD", "GRV", "HJX", 
        "IUP", "TSU", "HVF", "NJG", "HAL", 
        "SRX", "GGQ", "QPC", "TGZ", "VDO", 
        "GRK", "IJC", "IPV", "LJW", "ZME", 
        "GJX", "GCA", "SPH", "YLS", "OOB", 
        "RYX", "ZFS", "ZWM", "LNB", "NBP", 
        "XGS", "FRU", "DAP", "JOV", "AES", 
        "JTW", "ADC", "ZLL", "ENH", "RQS", 
        "NPR", "LVH", "ZHI", "ZSI", "ADW", 
        "GBB", "DPR", "IGN", "XTI", "OMN", 
        "KCC", "DWD", "VUS", "VOX", "BDH", 
        "AJO", "ICC", "TVJ", "XHK", "CHB", 
        "EZY", "DRH", "LXR", "OCT", "RKU", 
        "CMY", "CCR", "QPS", "DUX", "HHV", 
        "TRO", "EJX", "PMN", "CKB", "WSB", 
        "TMU", "ZCO", "KFU", "ODP", "HGJ", 
        "AXM", "BDF", "KBX", "RVP", "IEI", 
        "GNV", "DRH", "LAT", "IUL", "EHZ", 
        "PQJ", "CAJ", "AHL", "MXG", "TDO", 
        "QJJ", "XHQ", "BMH", "OXV", "KYZ", 
        "ESW", "GQS", "CCE", "FZE", "BDM", 
        "QXV", "WDQ", "DZS", "VJP", "OAL", 
        "ZAU", "QHK", "XTE", "ATJ", "BDJ", 
        "HCQ", "BIS", "QEF", "KYQ", "LSO", 
        "MQB", "QBV", "NNH", "UBI", "WUE", 
        "RIW", "FOS", "YGS", "PED", "TVG", 
        "OEB", "HMI", "LEZ", "MPQ", "BXZ", 
        "QDK", "NTW", "TOD", "VMX", "VUD", 
        "GZQ", "KCT", "JKP", "GUX", "NYM", 
        "POC", "PEY", "ZVC", "FFE", "SMB", 
        "MDC", "LMW", "YIN", "LST", "ZRT", 
        "FEG", "ZHM", "JSH", "LAI", "HVM", 
        "GBU", "DLE", "HRT", "JDU", "TYK", 
        "QRN", "QDK", "IVU", "HNM", "COD", 
        "WPL", "THG", "MRF", "GXI", "GNL", 
        "USJ", "PNQ", "XXB", "UJT", "XUW", 
        "ZAG", "QTF", "MGW", "BOC", "WQJ", 
        "IHG", "BPG", "NOE", "XQV", "AST", 
        "YRU", "TQP", "LJX", "FRL", "VUA", 
        "QCG", "HHO", "POE", "TSA", "JPJ", 
        "JOP", "RVH", "NTB", "MEZ", "YXD", 
        "JYF", "DEU", "IFL", "IHM", "RZR", 
        "BBT", "CPJ", "AWC", "BUD", "IBF", 
        "IUL", "MSE", "DXX", "ZFK", "GOC", 
        "XCK", "UCP", "XBZ", "VSX", "GER", 
        "SBL", "RAN", "XSA", "DGL", "FGF", 
        "GWB", "OYP", "RAP", "SYF", "CJC", 
        "VOU", "FMS", "SYA", "TNQ", "EGA", 
        "JIL", "IQY", "MKX", "VMM", "BNI", 
        "LIX", "WUB", "CKH", "XHG", "EAM", 
        "ALZ", "BDU", "ANN", "VLW", "WUY", 
        "OIO", "WAA", "BKA", "OCU", "FZB", 
        "JJP", "BKM", "TVV", "UXX", "JYU", 
        "IDH", "GBU", "JBI", "KJX", "LQW", 
        "SWD", "CFD", "CMW", "BQN", "KVH", 
        "XRJ", "OXV", "VAX", "CPT", "ZOT", 
        "DFQ", "NTQ", "BKI", "SVG", "TPD", 
        "FJF", "CQX", "CWN", "CCN", "VGG", 
        "CUI", "DES", "LHU", "GWU", "ZME", 
        "LBM", "PVJ", "ONU", "WUR", "OMQ", 
        "JDV", "NUO", "ACA", "HND", "KWK", 
        "QMG", "EAG", "ZGE", "SYI", "ZOV", 
        "JZB", "THP", "GET", "LTH", "EPI", 
        "VTA", "LRI", "EYC", "XKI", "YGS", 
        "DIS", "UMX", "DFM", "WKT", "HKN", 
        "ONA", "XNQ", "ZQJ", "YMF", "HNR", 
        "ALO", "ALP", "MTB", "AHU", "ATX", 
        "KIF", "XZN", "CNO", "DGB", "UGQ", 
        "UKT", "BNO", "UVU", "DNB", "CUO", 
        "FKJ", "SIK", "MBC", "ANL", "PSV", 
        "QBZ", "FSL", "DAN", "RMN", "KMC", 
        "YQB", "LLL", "QGC", "NES", "SFR", 
        "YVY", "QJJ", "KZW", "EQA", "NUO", 
        "XMB", "DZI", "XCX", "ZZW", "RRB", 
        "HLF", "EMY", "LMF", "TQR", "DZV", 
        "HSM", "DPJ", "DNH", "TAP", "YBR", 
        "LEV", "HPK", "NYK", "ELI", "PWO", 
        "UMV", "SZF", "GPS", "XCZ", "PCD", 
        "QAV", "YBB", "AKX", "FGJ", "MGV", 
        "KXH", "VVS", "IVL", "VCF", "YUW", 
        "IBH", "PAR", "XNK", "WNH", "ELC", 
        "EXT", "RXJ", "LZC", "EKZ", "SUO", 
        "TKS", "XIC", "EHB", "IVY", "WTG", 
        "MRZ", "FYJ", "IYT", "ECH", "JFJ", 
        "QMF", "EVN", "IGI", "QYF", "YOZ", 
        "JWW", "TRV", "FUD", "UFB", "CNU", 
        "NZS", "BGH", "TVT", "ABA", "BCA", 
        "TJB", "VQH", "LWU", "PNQ", "OUA", 
        "PZC", "BCV", "VOU", "AME", "QQQ", 
        "BQX", "QWD", "EGX", "VKG", "GWP", 
        "BOJ", "HSG", "QCB", "JNF", "YMK", 
        "HJN", "QZY", "ASR", "IFE", "QGK", 
        "DVW", "YSA", "HGT", "LCP", "WHJ", 
        "OHW", "KMF", "YDY", "EYG", "AGI", 
        "HIE", "SWM", "NQS", "HQN", "GVO", 
        "SUC", "WHD", "MSX", "GWS", "LSF", 
        "SSA", "LJX", "VMU", "EZV", "RHU", 
        "AZV", "RYV", "TRQ", "FWZ", "TAY", 
        "YPN", "ZZW", "ZHQ", "WUI", "CTN", 
        "ZKC", "XEW", "WKV", "ZYO", "CZK", 
        "TIP", "QKC", "OEY", "JLI", "KGU", 
        "ULL", "ITI", "ZQW", "JOD", "JHA", 
        "JAZ", "FIT", "VDT", "MJA", "PVR", 
        "ZGW", "NCY", "ADD", "QEI", "COL", 
        "MOS", "FQH", "WFN", "EMC", "GHE", 
        "PKP", "SFT", "IQT", "OYL", "PZI", 
        "NLN", "THJ", "YJG", "DQK", "ZJW", 
        "JJI", "ZDM", "UTS", "TDZ", "NYO", 
        "QIU", "CNV", "QRP", "WUI", "CZZ", 
        "UKT", "SKO", "DHG", "NXJ", "GMV", 
        "UJQ", "WZC", "USH", "STH", "NGL", 
        "DNK", "MDL", "ONT", "LXH", "JSW", 
        "ERO", "NBA", "IQO", "ZKB", "WHR", 
        "GFB", "NLH", "FBT", "SBG", "ZUA", 
        "JAJ", "HEO", "OIQ", "UND", "SMI", 
        "HWY", "PXF", "WTP", "SWC", "YII", 
        "TKY", "JRK", "ETN", "YRK", "TRF", 
        "VFY", "UTB", "MXC", "WVV", "MLE", 
        "BDU", "OYI", "ZDX", "PHK", "RNU", 
        "INR", "LXK", "HUR", "CNZ", "PFV", 
        "KJB", "AKU", "HRT", "HOB", "SLD", 
        "DPP", "ZWP", "MLY", "EAL", "UFG", 
        "HKZ", "ASI", "GEP", "UZR", "NHW", 
        "HXD", "OUW", "WTK", "CBU", "TEG", 
        "QLE", "DPS", "UIW", "QBG", "TSF", 
        "CBJ", "DQC", "HPF", "ZYO", "HVD", 
        "AVL", "ZMA", "MOY", "QNM", "HJD", 
        "ZDI", "NAU", "SKU", "DRA", "SKL", 
        "KRE", "UMR", "WPC", "QYQ", "BPY", 
        "TFT", "TBZ", "IQH", "PEM", "BXF", 
        "MPC", "PXT", "QJV", "GUW", "KYJ", 
        "KJF", "QJP", "DFR", "ANI", "BRJ", 
        "JXQ", "IZD", "USA", "LKZ", "UXP", 
        "NOX", "ZEU", "SXL", "NHQ", "TDI", 
        "JAA", "KEI", "XZS", "GPI", "JTR", 
        "PPS", "TWI", "KTF", "LWJ", "ZCS", 
        "NPU", "PXG", "RSV", "ILQ", "DOY", 
        "NEA", "HLG", "VAQ", "WRE", "JPS", 
        "CUH", "MWT", "NKP", "VUH", "BAU", 
        "MGJ", "QFI", "ERE", "NSN", "SBT", 
        "AVN", "DIU", "ZTE", "UZX", "TGQ", 
        "VIU", "PYZ", "ATT", "NBY", "RDT", 
        "MOS", "MRL", "YZK", "VMM", "JYW", 
        "JCR", "GIZ", "NJJ", "HAS", "VHK", 
        "BAQ", "HNW", "CHF", "LBJ", "ZSG", 
        "IQZ", "NHL", "INP", "NEQ", "WTD", 
        "VMA", "PYX", "MVC", "VZE", "YUQ", 
        "KBG", "WLQ", "FHL", "DDU", "EWL", 
        "KGD", "CSO", "QNN", "HBE", "JDS", 
        "DXH", "ZAA", "NKO", "BII", "EOL", 
        "FIS", "QUN", "KBI", "YLO", "KWV", 
        "ROH", "QSA", "EBR", "OOQ", "LOD", 
        "PPX", "MKH", "HZK", "NQB", "VKW", 
        "ZSY", "OHN", "SRJ", "WGK", "OXP", 
        "OCH", "SAN", "VFR", "MEX", "DWK", 
        "TJA", "QTK", "KZW", "OTE", "RFD", 
        "NBE", "CXV", "TBD", "JUJ", "YRV", 
        "XDN", "TVE", "PXD", "KEK", "RZL", 
        "LTQ", "KEZ", "OKV", "EJV", "NAK", 
        "YKH", "CTH", "PXQ", "EVE", "JNK", 
        "ORA", "TOA", "EMG", "KEX", "FQJ", 
        "TDP", "SGQ", "SCE", "JGL", "LTL", 
        "TCM", "JWD", "FKY", "SIU", "BCT", 
        "VBL", "CAL", "UDQ", "YUN", "MWD", 
        "TOU", "WIW", "NZA", "YFU", "HVY", 
        "KGQ", "DJP", "OAR", "FPH", "XRG", 
        "SQG", "GQT", "ZOP", "IYO", "PCL", 
        "UYB", "JFI", "GAP", "ETS", "VPD", 
        "VZQ", "HKT", "QRV", "CJW", "PDZ", 
        "KPO", "HDA", "EMB", "ZGZ", "WBR", 
        "LEG", "JCJ", "XNJ", "UAD", "VTQ", 
        "RKZ", "XBY", "NBJ", "RMU", "GNM", 
        "TNT", "CKJ", "YWH", "BLD", "DSJ", 
        "MOO", "JWZ", "HBN", "ARR", "AIY", 
        "WTX", "JTE", "XMK", "EMS", "EOB", 
        "SPI", "BAU", "LAV", "KJS", "BIP", 
        "RJM", "WTY", "XCH", "TZC", "CEH", 
        "XDY", "ZMP", "AGR", "CCH", "YTM", 
        "KHH", "CZS", "LTS", "ZXK", "QXT", 
        "QQX", "MBB", "LJP", "EMQ", "ZBV", 
        "RBW", "SBD", "GNH", "TDS", "BIT", 
        "ANB", "HDV", "BFX", "UYV", "RHT", 
        "HHR", "GJX", "FBF", "UAW", "UOI", 
        "OOL", "IFJ", "FNV", "KJU", "MIP", 
        "LDV", "LLI", "JIY", "QXS", "OHN", 
        "CQR", "BMN", "LIW", "MNB", "PGQ", 
        "XMP", "HXY", "CRY", "EEK", "IXB", 
        "OEM", "WPH", "ELS", "IUD", "MNI", 
        "DUR", "CIU", "YPQ", "OEA", "YKL", 
        "UJW", "IJP", "VSV", "UPF", "XFA", 
        "IPN", "VYW", "UCW", "RQQ", "BHI", 
        "ZPQ", "LIX", "RVA", "PZV", "NPB", 
        "FYU", "PHO", "WIV", "MHD", "IPM", 
        "OVX", "HAJ", "IPI", "JOQ", "JYZ", 
        "KMG", "LVE", "EGK", "MEC", "FSP", 
        "UUC", "MUZ", "EOQ", "NUT", "FFF", 
        "RIS", "WFT", "UCL", "NPF", "ZWK", 
        "XVG", "CZV", "QSK", "SHG", "HLE", 
        "MBK", "JBL", "CEW", "ELX", "RLD", 
        "KSN", "SQY", "QIY", "HKY", "MIL", 
        "JYA", "QCU", "ORD", "TFJ", "HDH", 
        "UBJ", "CVN", "REK", "PLK", "WYO", 
        "WBL", "PXX", "ZXH", "QKW", "DPD", 
        "LRV", "OIH", "IYL", "QCX", "QTH", 
        "KJS", "TRF", "XSU", "DJX", "ESX", 
        "PPF", "NAI", "OPF", "DTE", "MQS", 
        "XJS", "RTP", "DVV", "UKW", "PIO", 
        "OYM", "MUI", "JPI", "SEY", "AJE", 
        "TXC", "BOY", "AMJ", "BAL", "ZUA", 
        "EEJ", "RGA", "PRY", "EHL", "EBX", 
        "VKG", "VHG", "IVS", "GIR", "NSQ", 
        "HMI", "KHU", "ZPN", "HGV", "SLD", 
        "OXU", "DZR", "VQM", "JHB", "NLA", 
        "PXB", "FSF", "EEA", "CPM", "GLI", 
        "NFG", "HTE", "ZKE", "XSV", "PFE", 
        "BHD", "RBC", "XAA", "STL", "REY", 
        "JKA", "HLI", "QZC", "PQJ", "HUT", 
        "QYW", "PLQ", "MFY", "GZK", "EGQ", 
        "CVO", "AXZ", "GHS", "ZHF", "VQA", 
        "MLI", "EJG", "GAD", "RKO", "PEL", 
        "VLM", "DZU", "RUY", "KTI", "URQ", 
        "FOW", "PMK", "XGU", "HGS", "DMQ", 
        "HPV", "ZFZ", "CLS", "PRR", "OTP", 
        "OJF", "LJJ", "PBC", "TZP", "IJY", 
        "VQO", "AQG", "CAY", "WIY", "ZZG", 
        "YUM", "FEL", "ETB", "LEY", "ZOQ", 
        "DOH", "HGR", "UGI", "LDY", "PNP", 
        "NQA", "JLR", "NAW", "PER", "ZVC", 
        "GRB", "IVP", "ING", "FZS", "MSH", 
        "VQN", "NVF", "LPL", "MNF", "HFL", 
        "BDQ", "SCO", "NYV", "GOW", "YKB", 
        "MJO", "FAF", "MWP", "ZLC", "ECH", 
        "QRO", "TKZ", "RST", "UVT", "QYN", 
        "ZFC", "PWD", "XVF", "NYZ", "YON", 
        "KFR", "QVM", "HKF", "XEA", "YOE", 
        "CLC", "COQ", "JAD", "AZT", "ZIT", 
        "CIX", "YCW", "GCU", "RLX", "MBJ", 
        "KLY", "TBW", "JQW", "GVD", "VVX", 
        "UJH", "EMW", "EFJ", "EWZ", "CJO", 
        "BWW", "KBU", "WQY", "SUH", "JUF", 
        "RKY", "RSS", "AWR", "UAT", "YZQ", 
        "WON", "MSV", "ZJE", "LKN", "ILK", 
        "QBB", "OXB", "OLS", "WDY", "KAL", 
        "IFC", "YJQ", "IFJ", "IQY", "IIA", 
        "HWR", "ULL", "QIX", "GMT", "OFM", 
        "KWH", "TCN", "ISW", "GFL", "FRB", 
        "KIY", "NYF", "KSM", "XIV", "MGE", 
        "OEY", "HOP", "OMV", "RTU", "PKZ", 
        "HGR", "QFP", "VCJ", "YAR", "GLD", 
        "HJJ", "HFU", "ZKE", "JGS", "XZE", 
        "WXT", "YID", "EFY", "LPP", "XJF", 
        "XEL", "GYA", "XMC", "ILY", "LSZ", 
        "BEC", "ELQ", "BUG", "MKI", "YVP", 
        "ECW", "XMM", "LDG", "TIP", "AAK", 
        "UPT", "PVL", "BHZ", "UNU", "QQQ", 
        "CEI", "TTT", "DMY", "BGR", "YRW", 
        "HMD", "JKU", "DGG", "CNY", "EFL", 
        "DXJ", "HZW", "IFQ", "HWH", "XCX", 
        "ERA", "LRT", "VGX", "ZGH", "OOY", 
        "EOK", "LDA", "AXW", "QDE", "DVA", 
        "KLM", "GPJ", "ADI", "FEL", "LBI", 
        "KQU", "RHF", "SJJ", "IKX", "XRQ", 
        "IWY", "KXY", "ZYK", "JLG", "SFW", 
        "PDX", "NNM", "DDA", "NZO", "VLK", 
        "HOX", "NBD", "RAO", "VOD", "BTA", 
        "YQN", "YUX", "FQR", "FTD", "RAN", 
        "IEP", "IYZ", "JOB", "FDD", "XAS", 
        "SVI", "RCN", "BTW", "LAX", "KDN", 
        "LZY", "UZW", "ZDB", "FTM", "JRT", 
        "FJW", "JGU", "FEF", "GQW", "DSA", 
        "DGV", "QOD", "WPU", "CGP", "CKQ", 
        "QJI", "ZAW", "VRO", "MUQ", "HAB", 
        "JSK", "AXS", "PBU", "QOW", "DWZ", 
        "HGY", "CBS", "FIB", "JDV", "SZC", 
        "XSC", "ZVJ", "BBP", "QZI", "LWX", 
        "PZL", "MKB", "LMA", "NNU", "DEC", 
        "BQI", "QFT", "KIO", "UFZ", "COP", 
        "FUH", "NEI", "WDA", "JQX", "RLW", 
        "KMS", "CBW", "KCC", "WDV", "TLI", 
        "PTT", "ZAD", "TNG", "PCS", "KHO", 
        "TLD", "TZT", "EZN", "CTK", "RSX", 
        "WNR", "DXP", "SCT", "LIE", "NXX", 
        "JNG", "TCI", "JHD", "IQU", "UJV", 
        "KDO", "UCO", "RLM", "UON", "JRQ", 
        "ZEQ", "EBV", "XIB", "REX", "GBB", 
        "JXR", "DZQ", "FDP", "DVE", "WNS", 
        "PAN", "FDI", "TMY", "OBG", "RVE", 
        "JCJ", "BLB", "DKJ", "ZBP", "BTT", 
        "CXB", "KSP", "ZNR", "ZJB", "QGP", 
        "TPW", "OBN", "OTW", "ONE", "ABM", 
        "ZRR", "HMT", "VUG", "MYF", "EKZ", 
        "FLT", "WJC", "CZO", "QOH", "LYO", 
        "DZD", "ETZ", "HPV", "ZCH", "MTC", 
        "JAL", "QCU", "IOR", "FSZ", "JIC", 
        "YVP", "CQM", "PWV", "RIV", "CVW", 
        "KJS", "ICI", "MYW", "RKB", "UMC", 
        "XMG", "KZU", "WXL", "GGY", "VBF", 
        "XLT", "GBT", "XDJ", "AKT", "HSB", 
        "DRN", "EDY", "PMV", "ODW", "SOJ", 
        "TWI", "JER", "ZEP", "PHC", "HTL", 
        "WYH", "IAG", "EOV", "UYF", "FBD", 
        "PWZ", "JIO", "VFV", "JDM", "XYW", 
        "BMF", "BSY", "QZB", "FXM", "RBT", 
        "TLT", "HNV", "TII", "VHN", "FSP", 
        "BGG", "NQZ", "TTO", "XOK", "FEY", 
        "KGP", "ICU", "EMP", "PTD", "UWE", 
        "QJH", "TNU", "FGX", "JYY", "PHU", 
        "TCA", "FWR", "CEM", "SML", "WLA", 
        "XKT", "SWV", "VMN", "AHX", "UIA", 
        "ERA", "LAX", "PXV", "KGE", "QIO", 
        "HXG", "PGS", "JTW", "XJV", "IFE", 
        "KYN", "WNU", "KIK", "OKT", "NYM", 
        "QRX", "VJG", "QUX", "VXG", "YWL", 
        "VKP", "OMW", "BLH", "HHB", "FBJ", 
        "WMD", "NFH", "PQO", "HDH", "WVB", 
        "LVN", "XKN", "QWW", "PVF", "ZGJ", 
        "GFW", "UBT", "VKQ", "QBA", "VME", 
        "TKS", "AQH", "TFT", "BUV", "YSR", 
        "KXN", "JEP", "AEA", "BEY", "IBE", 
        "TYT", "NVP", "TRX", "DZS", "SXI", 
        "MHN", "SLZ", "IJY", "ZSM", "YXL", 
        "VOG", "AMW", "NYA", "OPY", "MFL", 
        "AXW", "WYW", "XZV", "EGZ", "PIO", 
        "AZZ", "NJY", "DXJ", "ZVJ", "EFX", 
        "DJO", "TUY", "JNZ", "WFK", "WXM", 
        "EGB", "ORV", "QLA", "NYC", "LLC", 
        "PUN", "NPE", "DNI", "NIM", "GCM", 
        "ITR", "BQQ", "UUT", "NSK", "KCW", 
        "GPF", "YZG", "UKS", "WSH", "XXB", 
        "WCW", "IEZ", "NJM", "CDG", "PHW", 
        "JAI", "YGC", "PHV", "ORN", "AIJ", 
        "LFM", "VWL", "AKJ", "HQF", "VOO", 
        "HTI", "NYD", "LLQ", "PZA", "WXI", 
        "KJQ", "LIG", "DTG", "YJB", "YPS", 
        "LBO", "EBO", "HJS", "ZPZ", "VIJ", 
        "FHE", "TDJ", "YFF", "KNU", "XVK", 
        "KOE", "UZW", "NCC", "NQO", "XAJ", 
        "FQO", "WYN", "OGP", "DZF", "SFH", 
        "JXP", "HBQ", "XYJ", "HJC", "OOB", 
        "DTK", "UAW", "WEC", "WQT", "PJX", 
        "EQM", "YDX", "HDD", "NKW", "PRH", 
        "TPG", "EGC", "IWH", "PZH", "FPI", 
        "CNQ", "BWN", "AJW", "RLW", "IYS", 
        "RWE", "SWV", "BGH", "DHN", "EFE", 
        "SMC", "NLI", "QML", "JHD", "CAN", 
        "MUU", "PLY", "FGA", "IRR", "YOW", 
        "NVA", "RFK", "BLP", "FRU", "FFM" 
        ];

/**
 * The list of adverbs.
 * @const
 */
const _ADVERB_ = [
    "215", "855", "198", "956", "519", 
"101", "827", "699", "607", "443", 
"686", "948", "393", "616", "401", 
"901", "693", "774", "427", "753", 
"108", "955", "821", "316", "762", 
"246", "528", "902", "418", "559", 
"578", "566", "718", "614", "556", 
"247", "571", "350", "584", "966", 
"622", "986", "581", "118", "782", 
"964", "608", "876", "940", "521", 
"779", "946", "487", "564", "511", 
"318", "898", "775", "476", "970", 
"967", "808", "461", "675", "533", 
"900", "223", "611", "429", "338", 
"668", "545", "279", "440", "288", 
"383", "868", "602", "485", "842", 
"911", "981", "481", "776", "888", 
"623", "860", "640", "908", "464", 
"719", "542", "577", "379", "990", 
"525", "778", "196", "608", "370", 
"990", "637", "158", "327", "254", 
"803", "267", "527", "688", "174", 
"335", "810", "615", "622", "995", 
"849", "108", "550", "487", "324", 
"186", "633", "620", "348", "391", 
"822", "181", "291", "168", "201", 
"723", "927", "717", "478", "263", 
"450", "154", "554", "135", "839", 
"311", "870", "224", "514", "387", 
"756", "309", "149", "154", "465", 
"569", "540", "108", "484", "750", 
"562", "592", "981", "367", "493", 
"147", "657", "861", "219", "511", 
"460", "892", "905", "229", "754", 
"256", "329", "399", "432", "585", 
"346", "125", "464", "667", "208", 
"901", "413", "779", "170", "459", 
"217", "413", "858", "933", "903", 
"372", "129", "646", "528", "991", 
"758", "834", "673", "397", "710", 
"495", "688", "811", "908", "798", 
"386", "953", "779", "193", "703", 
"700", "642", "490", "981", "283", 
"376", "525", "491", "823", "862", 
"832", "944", "138", "253", "537", 
"431", "516", "171", "176", "263", 
"162", "200", "570", "400", "214", 
"653", "497", "386", "800", "326", 
"425", "567", "869", "456", "341", 
"919", "823", "101", "470", "212", 
"261", "949", "896", "891", "819", 
"164", "184", "473", "157", "112", 
"483", "510", "983", "600", "389", 
"102", "205", "148", "452", "253", 
"913", "963", "570", "606", "563", 
"885", "736", "946", "606", "800", 
"193", "356", "429", "199", "160", 
"716", "320", "172", "391", "268", 
"209", "686", "670", "688", "640", 
"851", "398", "529", "429", "602", 
"985", "571", "851", "652", "629", 
"357", "720", "721", "411", "728", 
"942", "249", "935", "411", "695", 
"841", "260", "396", "559", "252", 
"360", "243", "324", "212", "182", 
"198", "825", "823", "368", "318", 
"702", "566", "326", "216", "418", 
"447", "331", "121", "826", "979", 
"774", "867", "601", "934", "422", 
"643", "400", "448", "911", "212", 
"531", "426", "912", "863", "104", 
"300", "910", "518", "751", "838", 
"433", "167", "871", "362", "627", 
"659", "398", "766", "845", "794", 
"440", "807", "641", "435", "214", 
"813", "883", "207", "364", "967", 
"128", "403", "698", "620", "920", 
"961", "939", "107", "120", "832", 
"206", "494", "940", "557", "949", 
"363", "910", "731", "822", "502" 
];

/**
 * The list of adjectives.
 * @const
 */
const _ADJECTIVE_ = [
    "AMI", "TDB", "EIN", "VNZ", "EEE", 
"FBZ", "MMB", "XAY", "TEF", "QOI", 
"UAC", "JUA", "OGY", "PRI", "PNV", 
"OMU", "ABX", "DXT", "GDM", "MWH", 
"WKC", "FIW", "NTR", "ASD", "HLQ", 
"UFD", "RXW", "UDK", "GGM", "OYX", 
"HRQ", "ZMG", "MKK", "BWD", "RPK", 
"GSG", "MUB", "KDB", "XPV", "MHO", 
"TQS", "IYS", "PFT", "JYO", "SFP", 
"KXX", "IZW", "BTL", "CHE", "OUP", 
"RRU", "JLV", "URX", "TVF", "SBQ", 
"TBU", "AIU", "QEA", "SOH", "KYF", 
"PSP", "PFH", "FBV", "GKJ", "MCA", 
"HMR", "PRJ", "IOW", "TUA", "HRK", 
"JNT", "ZLF", "QFT", "GCZ", "GWK", 
"NCO", "NCH", "OYA", "VKQ", "IGL", 
"TJG", "OBQ", "UQV", "SZS", "RED", 
"WAI", "RTI", "HWW", "VZR", "RVR", 
"XLU", "CLV", "TPQ", "JUF", "ZPZ", 
"BUE", "KCD", "JNY", "YCJ", "OLY", 
"VKN", "SPF", "DRZ", "TRO", "AGM", 
"MXM", "YBT", "FKU", "BCQ", "FNN", 
"LXF", "KUQ", "GEG", "OIE", "XMT", 
"EKG", "SMN", "IOO", "JRS", "ZBC", 
"FQL", "UFU", "JBF", "XJX", "RAO", 
"BJW", "KPZ", "FJS", "XGP", "OVX", 
"EJE", "MXS", "JFW", "NWP", "CRL", 
"PYJ", "WUV", "DNH", "FEZ", "IKX", 
"FBZ", "VPQ", "HBD", "DFG", "CFL", 
"OMG", "YGC", "QSU", "SVB", "ENQ", 
"MCR", "FIR", "BAP", "MTQ", "CRU", 
"IAM", "QJS", "ZOP", "ZLA", "QTM", 
"TRA", "IKT", "TJK", "OZO", "UOP", 
"MKE", "PSK", "XHN", "ADC", "MGQ", 
"HFA", "DKF", "DRH", "SMH", "LYT", 
"NCJ", "SHQ", "XFG", "EWM", "HLB", 
"SPB", "EFJ", "JOX", "OWU", "SFU", 
"OUG", "CFG", "LDU", "ELN", "DIU", 
"VXB", "FIL", "RNX", "WXQ", "FHR", 
"CDT", "LZB", "RJS", "PSQ", "QHO", 
"SRB", "EXB", "NNT", "SEC", "LTH", 
"DZO", "GDN", "DXL", "DNG", "XOC", 
"PAW", "LHY", "XNN", "IXW", "WQJ", 
"MRT", "OKH", "FRF", "PDR", "WPN", 
"PVM", "ZLJ", "XPX", "VKM", "BGU", 
"SYB", "JPB", "IGO", "FZB", "OMO", 
"XCE", "DKO", "AYZ", "TJZ", "OQV", 
"RMC", "SRT", "XIK", "YLQ", "WTC", 
"YOD", "MBQ", "DKR", "NVO", "FLU", 
"ZKD", "MWK", "YJO", "DLR", "YAJ", 
"CBL", "OGD", "GEU", "UJQ", "UZN", 
"POP", "JJP", "CXE", "KTH", "CJH", 
"HKN", "HID", "MII", "UGT", "QZO", 
"JZV", "VGT", "NGI", "MAC", "XKX", 
"TZU", "HRW", "YPI", "HWN", "HZR", 
"LSQ", "QKJ", "SFT", "OIU", "OLJ", 
"VVQ", "FVZ", "SEZ", "YMH", "OWV", 
"FSP", "CSY", "OTK", "FDO", "VJU", 
"VJA", "KZD", "RQA", "ZWA", "OHE", 
"SWR", "HFF", "NAC", "NSG", "PHS", 
"KTN", "WHU", "DBK", "AVD", "FPG", 
"BLZ", "ZLC", "PBH", "WPH", "JSP", 
"RLM", "OEO", "VRK", "UPA", "SYU", 
"DLG", "QDX", "SAM", "QYJ", "LOE", 
"WFP", "SAO", "WQH", "TJY", "UVU", 
"QAV", "OHF", "XZZ", "FDQ", "VXM", 
"LZZ", "MCO", "FRG", "BBI", "QDD", 
"IVC", "BUA", "GAQ", "XDH", "AEL", 
"EBX", "COA", "XTH", "YWM", "BRY", 
"GYF", "LCE", "AUZ", "CCA", "CYE", 
"GLB", "DOP", "EAH", "DXG", "HNU", 
"FHA", "WIF", "NUM", "IYC", "QOO", 
"KFU", "WSV", "KHB", "GTO", "OAO", 
"GGV", "ORI", "AOB", "INA", "DYI", 
"CEC", "IPA", "FYG", "SZD", "EFY", 
"TNW", "QKV", "XWS", "NKM", "JDF", 
"HPB", "CNT", "LEZ", "UGC", "BNT", 
"BWF", "ATU", "LKA", "SCN", "ZTC", 
"XVC", "GXO", "YXO", "FUP", "HPZ", 
"XWX", "ZPJ", "XJK", "MAE", "VHL", 
"NFS", "PFQ", "HHO", "ZFA", "MQY", 
"TBG", "KHU", "MEM", "DXS", "LAC", 
"QOU", "JSB", "DHE", "VQZ", "OWR", 
"LUR", "GIW", "SQM", "MUU", "QHB", 
"ZXZ", "CMM", "ZFA", "WIN", "NAW", 
"EGF", "NUR", "CUB", "TRR", "SIA", 
"NZQ", "OTN", "XRG", "QIN", "USC", 
"TJM", "RUN", "TIR", "XNT", "DUB", 
"YZX", "CZI", "HAR", "JGQ", "GEZ", 
"FNP", "SGD", "PEE", "SZC", "GWE", 
"XFS", "UHV", "AEW", "WTQ", "VBA", 
"MEO", "FCU", "DUX", "ANR", "ZEP", 
"OQD", "RAA", "ZJI", "PPS", "PQS", 
"SAR", "IKL", "ZFR", "KPG", "LZB", 
"UYY", "KQF", "ULR", "DBW", "AAD", 
"BSS", "WYX", "RXW", "AKB", "SUF", 
"HQF", "NQD", "DGF", "DGA", "XDI", 
"LET", "SON", "PDU", "NUS", "WOM", 
"MOV", "LFQ", "RRU", "JHA", "YFQ", 
"HOV", "WIT", "IOL", "UUO", "YQC", 
"JNX", "DIW", "JMR", "TZC", "JUU", 
"SAK", "VLN", "MCL", "PTQ", "MSF", 
"ACQ", "DQN", "LWU", "ANN", "VXD", 
"BAR", "VIG", "EZV", "GBL", "YUK", 
"FCF", "BWT", "UPX", "UMU", "WTH", 
"XSO", "MSE", "LKN", "KOP", "JSE", 
"KRK", "WRJ", "EYQ", "HHB", "NWF", 
"ZLR", "WOU", "OMN", "HQB", "GEZ", 
"KXN", "GPL", "VGZ", "GXS", "NYT", 
"OKM", "TZQ", "EYR", "OHB", "JKB", 
"EQR", "EZF", "AHD", "ERY", "LAM", 
"IFB", "UYS", "BAI", "HLN", "HUT", 
"JNE", "UFH", "WIA", "HFO", "FTF", 
"IUM", "SZH", "DPI", "CCY", "YFV", 
"ZLO", "LAB", "MGT", "LZU", "GWG", 
"AOL", "VLE", "EAJ", "GJU", "PQH", 
"HYI", "DTC", "NWK", "TLJ", "GNG", 
"NUB", "IEA", "QTH", "NXA", "VDV", 
"JFL", "KXM", "OWV", "WIL", "OGH", 
"XYE", "JOB", "HTE", "IJM", "ZEE", 
"FDW", "FAU", "DEB", "SIS", "IPV", 
"UXP", "LJC", "SAB", "ZSP", "AIJ", 
"MIU", "QFB", "DOT", "VZP", "KJR", 
"NNU", "CWQ", "YXP", "SGN", "KBJ", 
"JOJ", "JPT", "COG", "MCL", "QRD", 
"QRZ", "SUQ", "VMJ", "PYJ", "CHZ", 
"XDQ", "HDX", "EFO", "RLN", "OAR", 
"UDS", "HHJ", "FGN", "TFH", "LDW", 
"BKO", "BQF", "YPO", "OGG", "PKI", 
"ZQJ", "JGE", "SNQ", "GRT", "MJW", 
"JCA", "VUG", "ETM", "PCA", "HLM", 
"JQA", "YMK", "KRY", "BCI", "RUT", 
"NWM", "HRT", "HLW", "LLY", "QRY", 
"MLO", "QSZ", "QNF", "BRR", "CQE", 
"AIZ", "BEK", "RJE", "OOJ", "KQR", 
"LEX", "ETG", "TYK", "OLN", "KSP", 
"SOW", "IHI", "RFX", "NTZ", "ZQP", 
"LCN", "LRQ", "DGW", "NPH", "VHA", 
"DAW", "CBJ", "TXT", "MIM", "CUZ", 
"FRG", "FEF", "BCP", "RRM", "VFT", 
"TAH", "VRD", "VIE", "MRS", "FSC", 
"KDU", "MAF", "BYM", "OUF", "BGD", 
"AKB", "DXK", "GOH", "NTO", "NWV", 
"DHH", "AHN", "ZHJ", "RDX", "PYP", 
"MIG", "SYP", "QCZ", "TGQ", "ELX", 
"LVZ", "PLU", "GKS", "YHF", "PYN", 
"TBA", "KBQ", "EQR", "NUW", "WAQ", 
"XDB", "KCO", "MGV", "LCZ", "ULZ", 
"WXK", "WWT", "JFJ", "RTX", "WJK", 
"UCK", "ZOX", "CJJ", "SMJ", "VQZ", 
"CZO", "MWW", "DGQ", "VKT", "WOT", 
"MCM", "EST", "OCF", "SUD", "YAK", 
"UTR", "KQV", "PIG", "CIM", "CYH", 
"RHI", "HYV", "GET", "FXK", "XZJ", 
"HMK", "UKY", "BVV", "DDE", "FSX", 
"PHP", "PEV", "DIJ", "EKG", "OZQ", 
"WPN", "KWY", "TKB", "HSK", "YES", 
"DPD", "SXT", "WGX", "QUA", "CDQ", 
"KUN", "VFY", "AUL", "OOP", "DYU", 
"MRU", "DKT", "EHM", "FQB", "UJL", 
"BPC", "DZY", "NHH", "MAZ", "UPM", 
"YTY", "RVC", "OMU", "BTZ", "YIZ", 
"CBP", "MKQ", "ODW", "CHS", "XNE", 
"KGT", "VJD", "DDI", "TMN", "VQK", 
"GPD", "VYM", "YCP", "VTD", "JLW", 
"OZM", "QMA", "GFZ", "ZBL", "QOW", 
"AQG", "KMI", "DYE", "DIF", "POK", 
"ZBU", "QIP", "KAH", "RIL", "UTS", 
"WAM", "ZYO", "VPT", "OGB", "RXO", 
"JAS", "LEC", "NSU", "TKX", "XIJ", 
"OQM", "OJN", "SLL", "FEI", "KUH", 
"HDE", "NME", "PEK", "OBE", "KFB", 
"KVB", "TGO", "FTA", "MKQ", "KCJ", 
"WMP", "UVG", "THG", "VIR", "TCP", 
"YHQ", "XOF", "HZD", "ZXZ", "BJX", 
"GRC", "KHR", "ZJV", "HWC", "HLK", 
"YYA", "JCE", "VQX", "WVY", "PDE", 
"NIG", "YVR", "JFV", "XXP", "QNN", 
"HAA", "XJY", "HZU", "MUA", "TIU", 
"XFT", "RFS", "CUS", "YGV", "OTH", 
"VPV", "BUN", "RQB", "BRD", "PLX", 
"NHH", "HHY", "RFC", "GCS", "HFS", 
"MSQ", "SDG", "RCI", "JZZ", "XTN", 
"RFB", "FFX", "DXE", "JDS", "SRI", 
"VEM", "LGB", "OPF", "KTE", "WJV", 
"KEC", "TOF", "PQD", "WRS", "GXW", 
"UFH", "RJF", "UMD", "NZI", "UPV", 
"QZV", "EHY", "JXE", "JRO", "WPE", 
"JHX", "OIN", "BVQ", "BAG", "GOY", 
"FVT", "SUY", "NHC", "YEI", "DXQ", 
"BNC", "KTC", "YUQ", "JZP", "AHI", 
"XML", "LJX", "NLT", "SQC", "ETJ", 
"YEA", "JRW", "TJQ", "MWV", "SCY", 
"EHQ", "FKS", "JTV", "VTA", "BFV", 
"YUU", "EAU", "INH", "WIQ", "TQT", 
"SLO", "IMD", "TYR", "ONL", "SNQ", 
"DUA", "SIR", "CNK", "SBC", "NMX", 
"LOH", "QYZ", "YAP", "YFR", "HTJ", 
"PWO", "RHG", "HOQ", "CWN", "BPM", 
"EEL", "QTT", "JCB", "YAK", "ZIH", 
"HRO", "ZZE", "DRZ", "QUQ", "AJH", 
"FKF", "VRV", "OWG", "XXJ", "IWK", 
"LIR", "CLN", "DLO", "ZEG", "PZV", 
"YJD", "DIN", "IAO", "ONC", "QDN", 
"DPB", "DFY", "SQG", "IPU", "HNQ", 
"DNL", "MZA", "RGR", "ZWH", "WFO", 
"FCK", "EJC", "AKA", "ZRT", "PMV", 
"ZCR", "NLW", "QBD", "XHW", "XIM", 
"SKL", "RKV", "WGM", "VYV", "ILD", 
"XLC", "EKG", "QQN", "HPX", "BEL", 
"UFU", "NES", "GEC", "WUW", "OXV", 
"KVX", "LKJ", "DHD", "TBY", "KOJ", 
"FHI", "ZTX", "GEC", "SGI", "BWJ", 
"RZC", "TBO", "LIG", "VRW", "AKQ", 
"XDF", "ZFG", "VQS", "RJA", "UWB", 
"UJZ", "MTR", "SBW", "MJQ", "ZMO", 
"HRK", "ZEN", "NTJ", "EEY", "YYZ", 
"TJK", "CMT", "PAE", "PFA", "PDW", 
"XCV", "HZI", "IIH", "VDG", "BVQ", 
"EKZ", "YJC", "VPC", "QSU", "VBI", 
"GXC", "PCG", "RGN", "SPJ", "ILI", 
"TDE", "TJT", "GVV", "GVF", "GDY", 
"SAF", "YGS", "RLO", "CHY", "XYJ", 
"APE", "ZQA", "RUN", "ONN", "BMI", 
"KKW", "ERD", "UEP", "WEQ", "WGR", 
"NJH", "BWW", "OYK", "KKO", "AVR", 
"WNO", "FZW", "XUP", "UFN", "IXA", 
"ARG", "CGH", "HKC", "NKG", "HPN", 
"MNF", "HHC", "TDH", "RNN", "MBX", 
"ORA", "WLE", "LTW", "AWX", "QTB", 
"QYT", "ZJO", "SXK", "TUA", "BAU", 
"YIV", "FEJ", "CUQ", "WJN", "JSB", 
"KWU", "CWO", "MKV", "XPN", "GHI", 
"GNN", "FRC", "MVS", "MYR", "DJA", 
"KTF", "RXD", "PWI", "UYI", "KDG", 
"JOO", "ZVK", "IXF", "BOO", "ANT", 
"ZVZ", "XSY", "KCU", "WHY", "RHL", 
"LOC", "DHS", "ABS", "ZRL", "QKR", 
"CNW", "TZF", "MGI", "CHL", "NMB", 
"QZR", "VWJ", "TDC", "TAH", "SSG", 
"MLM", "PKW", "WNM", "USV", "ACW", 
"CCH", "EMX", "GEW", "TZR", "LUB", 
"JUC", "VNK", "NEB", "DIC", "PCT", 
"TMS", "THM", "DNF", "EML", "ZAT", 
"TST", "GNL", "STR", "FGH", "ALH", 
"KTP", "LVD", "LXH", "GQF", "YNR", 
"HGJ", "UGK", "TVG", "INX", "WJU", 
"FCX", "VGL", "RMQ", "EFF", "VBD", 
"JEJ", "YUM", "OMT", "ZEU", "WGA", 
"FYF", "PRI", "IJI", "SVY", "UEL", 
"VEM", "GMD", "DUQ", "NMS", "GYB", 
"KPI", "KZN", "IOG", "DQW", "GFV", 
"OIZ", "GHR", "MZM", "QKL", "PMG", 
"BSP", "TJU", "VLB", "VUO", "RVV", 
"DDE", "PCN", "NEF", "KQE", "MIU", 
"AXQ", "EPY", "XQG", "SIM", "BPQ", 
"WWZ", "HYF", "RWX", "EBA", "CYB", 
"RCU", "VQZ", "DGR", "BOC", "TWJ", 
"CQU", "WOB", "ZHO", "CYR", "MXY", 
"FZJ", "MLD", "SMG", "OCG", "CRQ", 
"UGW", "WFW", "LVH", "CMM", "ULO", 
"HSY", "CIA", "MIO", "DJT", "UBN", 
"EYO", "BUN", "OLA", "WIW", "TSG", 
"MIL", "ILR", "OEP", "DHY", "ZJN", 
"CSP", "AUM", "UTM", "HZZ", "WCV", 
"ANR", "JNC", "EGP", "IBR", "GNS", 
"UUS", "HZA", "TJU", "ETU", "UOR", 
"BGD", "WEE", "KRP", "EAE", "PQS", 
"GAJ", "IEP", "PYU", "GOO", "EHE", 
"NXZ", "AMQ", "MJT", "GJO", "NVA", 
"ZOB", "IOC", "BQW", "KAQ", "SEV", 
"CCX", "EYL", "TEF", "GLP", "AWY", 
"CDN", "QDK", "ALZ", "KFX", "XIN", 
"GJM", "JAF", "UFX", "KHQ", "XHH", 
"ART", "GFD", "LQZ", "ZRI", "JQJ", 
"YKM", "LSS", "BOT", "LOR", "CNQ", 
"WCJ", "VFC", "RWU", "YZB", "SGJ", 
"KCL", "FFF", "QQX", "YNI", "VWZ", 
"EFD", "ETF", "UVE", "YKC", "LLL", 
"UJB", "MFS", "JMT", "DPJ", "FQG", 
"WIO", "JVB", "IEC", "FYR", "GFW", 
"LRQ", "ECN", "IUT", "UOP", "QVD", 
"SZV", "QSM", "VOT", "MSR", "PKI", 
"GID", "ZCA", "DOJ", "GAO", "BTN", 
"KSH", "XWB", "LIV", "HHY", "YOY", 
"OCU", "FNC", "PDR", "UVB", "ZSB", 
"EAZ", "XSV", "VAQ", "CRE", "DWQ", 
"DBF", "MHP", "TIU", "DNC", "MRM", 
"NFS", "FGF", "ZZA", "KFV", "BEL", 
"XNJ", "XRQ", "IZK", "IWN", "MKI", 
"GKU", "HQJ", "GTY", "CXC", "WZU", 
"PUX", "MHQ", "BIW", "VBX", "YJG", 
"DAA", "GMG", "JFD", "SVF", "QER", 
"SBB", "BRR", "VDE", "DSX", "GFC", 
"OKD", "IIL", "IZG", "FQU", "VER", 
"DRE", "IQI", "RIN", "AJY", "ZLI", 
"DBJ", "JPE", "DXR", "YWM", "OXW", 
"AHA", "PVL", "URG", "MQL", "TXW", 
"HWG", "RXB", "CWM", "DLW", "FDZ", 
"KWH", "ESS", "ODY", "QZT", "VBC", 
"ZSA", "FHP", "RNK", "KFH", "VME", 
"BWH", "ANE", "RCU", "EUG", "IEJ", 
"XWE", "XLG", "FKZ", "CLK", "AFN", 
"BYL", "WRV", "EUK", "KNX", "BKR", 
"MAJ", "LJV", "WEQ", "XAS", "LHV", 
"UCT", "PZH", "AYD", "XOU", "RFV", 
"XUX", "ENC", "YUR", "FVZ", "EVP", 
"QWA", "MHM", "SIY", "ZEB", "ISW", 
"YVE", "EGF", "CZF", "RAZ", "ZCG", 
"XXO", "LEJ", "BXM", "NDX", "WHG", 
"MED", "XJP", "EVQ", "HVZ", "ZIF", 
"VLO", "NIR", "QRB", "PGG", "PUK", 
"BLW", "RPS", "BGP", "LBQ", "XSP", 
"JDB", "DEM", "ULA", "PDX", "BCL", 
"JNN", "IMT", "LDB", "HWH", "LIM", 
"IRY", "HJM", "SYS", "HXO", "KBD", 
"VHA", "DXT", "EFX", "HDR", "LOS", 
"NZG", "KZH", "VDU", "OGS", "XIT", 
"YXG", "JFZ", "MYD", "ENS", "PVA", 
"JPB", "IWR", "ZFZ", "RJM", "IRN", 
"YKA", "ALE", "MNT", "GGO", "ZJH", 
"KYU", "RKO", "APK", "ZVU", "LFT", 
"QKA", "VNK", "HBT", "WXD", "MHN", 
"FZI", "DSS", "TVG", "ITV", "EUU", 
"ENL", "XRD", "LBO", "KHU", "OLV", 
"RJM", "LYH", "CZZ", "CHU", "MXC", 
"DXK", "NYI", "CVO", "RUS", "ZZU", 
"BOM", "VJX", "KKP", "ZAX", "GVW", 
"FRM", "UDX", "PLM", "QNG", "FSP", 
"BSB", "TFM", "EPT", "RTS", "YLY", 
"JDQ", "SFW", "CMQ", "NDM", "OLY", 
"GDL", "NKV", "XSY", "CVY", "YLJ", 
"YWM", "TPH", "HNS", "GPA", "ONO", 
"AFI", "RMD", "AQS", "YZG", "IHU", 
"CCB", "SSE", "ZVF", "IJM", "IXP", 
"LPI", "HMD", "HWH", "CHY", "HAJ", 
"KQX", "TTD", "GOI", "IAN", "GBR", 
"ZNW", "LSR", "UDH", "QFC", "TCI", 
"WSE", "OQJ", "RVC", "VOC", "LWB", 
"FHV", "NEC", "PYC", "HMD", "XBP", 
"NWV", "EXR", "ZAO", "HZI", "YXX", 
"NHW", "IBK", "CAF", "XKB", "VHL", 
"OBO", "FWF", "JCZ", "BBF", "BAD", 
"ULG", "COS", "RNC", "ABS", "LXQ", 
"LTN", "GWV", "WQD", "OFX", "WLA", 
"HOS", "URT", "YNB", "VPR", "CRU", 
"BRO", "ICY", "ESH", "KRL", "YXG", 
"WKY", "RIO", "VXG", "KSB", "SDW", 
"TRR", "CLT", "YGV", "KDF", "LFF", 
"OXC", "IML", "IWE", "FLJ", "HOT", 
"HJD", "RQX", "JHV", "YJU", "GZP", 
"HHT", "NJN", "NND", "JZT", "ORR", 
"VTR", "OIV", "MBJ", "CUT", "DKH", 
"KAL", "LOR", "POQ", "YII", "URD", 
"CJQ", "WMH", "FFQ", "WCK", "BZA", 
"FLI", "FPF", "UJD", "WDF", "INT", 
"MNU", "QPS", "CXX", "JWL", "MAW", 
"KVM", "IHG", "TFI", "YTS", "PJO", 
"ZQF", "BOG", "POW", "MUA", "EJU", 
"DRN", "UVM", "UOK", "DRT", "CPK", 
"DQJ", "TCK", "LOD", "QOM", "NXH", 
"JMH", "PZG", "KEJ", "GFM", "OEJ", 
"EOS", "SCW", "OTF", "JWF", "LFH", 
"UQX", "QER", "BDD", "XEY", "AOY", 
"CGB", "QCX", "TXT", "YCU", "OML", 
"UDW", "PWJ", "KJG", "OLK", "TKS", 
"ORR", "KYF", "EBH", "HAM", "CCA", 
"BKH", "GJU", "TQT", "UMV", "TLL", 
"RHS", "NUD", "OWS", "OWB", "RWK", 
"YER", "NCU", "PGZ", "UDN", "IBR", 
"OQX", "FJR", "AXT", "VEN", "MGV", 
"ULN", "ZWC", "DYF", "HYW", "XQK", 
"OXS", "UWU", "LDZ", "KIG", "FZR", 
"SGI", "ICT", "UTB", "FVU", "MED", 
"ZAP", "PSB", "QLK", "FBO", "XDT", 
"RTO", "OPE", "RUM", "YDD", "NEQ", 
"DGB", "APY", "TIU", "ICY", "HLT", 
"CTQ", "DPX", "PUD", "BPI", "ODY", 
"MBZ", "QIY", "ELD", "PKE", "NXS", 
"GFO", "OJB", "FXQ", "GXI", "YYS", 
"NUX", "DXL", "COW", "IDT", "IXV", 
"QRD", "FYR", "IEI", "EHF", "QZH", 
"TVZ", "WDW", "WRA", "GKT", "SOT", 
"AJN", "OCH", "XVX", "TIX", "LRJ", 
"TQR", "DCS", "YKY", "JRA", "OTI", 
"LZE", "QSH", "JZP", "XTY", "KPM", 
"MIU", "ZCQ", "ODM", "KST", "PFY", 
"HGA", "JCC", "RMF", "GRL", "FPA", 
"VWC", "TBX", "ZOX", "YFA", "ZVA", 
"ZEO", "OJS", "WJT", "XIN", "YFM", 
"RLH", "VMM", "VQC", "UOG", "QFD", 
"CHH", "LXS", "ZTI", "GIT", "CJC", 
"GJY", "TCL", "DDA", "WEV", "LZL", 
"GSU", "CAF", "TSC", "HYP", "GHU", 
"MGE", "DDP", "NGN", "ZHT", "UHP", 
"RHG", "EMO", "DQC", "PFU", "XOZ", 
"KQQ", "DOK", "UFW", "BGZ", "LSM", 
"IRX", "UPD", "ZQV", "ZWU", "YCS", 
"AGC", "LAV", "OTB", "ZYO", "UNF", 
"KLZ", "JFL", "ZBQ", "KZN", "NFB" 
];

/*
const _PRONOUN_ = [
];
*/

/*
const _CONJUNCTION_ = [
    'And', 'Or', 'For', 'Above', 'Before', 'Against', 'Between'
];
*/

/**
 * Maps a string (category name) to the array of words from that category.
 * @const
 */
const CATEGORIES = {
    _ADJECTIVE_,
    _ADVERB_,
    _PLURALNOUN_,
    _VERB_

//    _CONJUNCTION_,
//    _NOUN_,
//    _PLACE_,
//    _PRONOUN_,
};

/**
 * The list of room name patterns.
 * @const
 */
const PATTERNS = [
    '_ADJECTIVE__PLURALNOUN__VERB__ADVERB_'

    // BeautifulFungiOrSpaghetti
    //    '_ADJECTIVE__PLURALNOUN__CONJUNCTION__PLURALNOUN_',

    // AmazinglyScaryToy
    //    '_ADVERB__ADJECTIVE__NOUN_',

    // NeitherTrashNorRifle
    //    'Neither_NOUN_Nor_NOUN_',
    //    'Either_NOUN_Or_NOUN_',

    // EitherCopulateOrInvestigate
    //    'Either_VERB_Or_VERB_',
    //    'Neither_VERB_Nor_VERB_',

    //    'The_ADJECTIVE__ADJECTIVE__NOUN_',
    //    'The_ADVERB__ADJECTIVE__NOUN_',
    //    'The_ADVERB__ADJECTIVE__NOUN_s',
    //    'The_ADVERB__ADJECTIVE__PLURALNOUN__VERB_',

    // WolvesComputeBadly
    //    '_PLURALNOUN__VERB__ADVERB_',

    // UniteFacilitateAndMerge
    //    '_VERB__VERB_And_VERB_',

    // NastyWitchesAtThePub
    //    '_ADJECTIVE__PLURALNOUN_AtThe_PLACE_',
];

/**
 * Generates a new room name.
 *
 * @returns {string} A newly-generated room name.
 */
export function generateRoomWithoutSeparator() {
    // XXX Note that if more than one pattern is available, the choice of 'name'
    // won't have a uniform distribution amongst all patterns (names from
    // patterns with fewer options will have higher probability of being chosen
    // that names from patterns with more options).
    let name = randomElement(PATTERNS);

    while (_hasTemplate(name)) {
        for (const template in CATEGORIES) { // eslint-disable-line guard-for-in
            const word = randomElement(CATEGORIES[template]);

            name = name.replace(template, word);
        }
    }

    return name;
}

/**
 * Determines whether a specific string contains at least one of the
 * templates/categories.
 *
 * @param {string} s - String containing categories.
 * @private
 * @returns {boolean} True if the specified string contains at least one of the
 * templates/categories; otherwise, false.
 */
function _hasTemplate(s) {
    for (const template in CATEGORIES) {
        if (s.indexOf(template) >= 0) {
            return true;
        }
    }

    return false;
}

/*
function findDuplicates(array) {
    var dups = array.reduce(function (acc, cur) {
        if (!acc[cur]) {
            acc[cur] = 1;
        } else {
            acc[cur] += 1;
        }

        return acc;
    }, {});
    for (const word in dups) {
        if (dups[word] > 1) {
            console.log(`Duplicate: ${word} ${dups[word]}`);
        }
    }
}
findDuplicates(_ADJECTIVE_);
findDuplicates(_PLURALNOUN_);
findDuplicates(_VERB_);
findDuplicates(_ADVERB_);
var combinations = _ADJECTIVE_.length * _PLURALNOUN_.length * _VERB_.length * _ADVERB_.length;
console.log(`${combinations} combinations (${Math.log2(combinations)} bits of entropy)`)
*/
